# Site settings
title: Jimmie Gmaz
email: jim.gmaz@gmail.com
description: Personal webpage
baseurl: "/about"
url: "http://jgmaz.github.io"

author:
  name     : 'Jimmie Gmaz'
  email    : jim.gmaz@gmail.com
  url      : http://jgmaz.github.io

github: https://github.com/jgmaz/jgmaz.github.io
google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
