# Site settings
title: Jimmie Gmaz
email: jim.gmaz@gmail.com
description: Personal webpage
# baseurl: "/about"
url: "http://jgmaz.github.io"

#author:
  #name     : 'Jimmie Gmaz'
  email    : jim.gmaz@gmail.com
  #url      : http://nandomoreira.me
  #facebook : http://facebook.com/fernando.dev
  linkedin  : https://www.linkedin.com/in/jimmie-gmaz/
  twitter  : https://twitter.com/j_gmaz

#github: https://github.com/nandomoreirame/zetsu
#disqus_shortname: "fernandomoreira"
google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
